<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, useSession, setCsrfToken } from './api'
const session=useSession(),route=useRoute(),router=useRouter()
const sections:Record<string,string>={overview:'运营概览',games:'游戏分区',categories:'商品类型',products:'商品管理',home:'首页配置',orders:'订单查询',partnerApplications:'陪玩申请',partners:'陪玩档案',audit:'操作日志'}
const section=computed(()=>String(route.params.section||'overview'))
const rows=ref<any[]>([]),total=ref(0),page=ref(1),q=ref(''),enabled=ref(''),gameFilter=ref(''),categoryFilter=ref(''),user=ref(''),status=ref(''),from=ref(''),to=ref('')
const games=ref<any[]>([]),categories=ref<any[]>([]),products=ref<any[]>([]),stats=ref<any>({}),busy=ref(false),saving=ref(false),error=ref('')
const username=ref(''),password=ref(''),dialog=ref(false),form=ref<any>({}),detail=ref<any>(null)
const writable=computed(()=>['games','categories','products','home'].includes(section.value))
// 陪玩相关
const partnerApps=ref<any[]>([]),partnersList=ref<any[]>([])
const appStatusFilter=ref('')
const assignPartnerId=ref<number|null>(null),assignDialog=ref(false),assignOrder=ref<any>(null)
// 订单 CRUD
const orderDialog=ref(false),orderForm=ref<any>({}),customersList=ref<any[]>([]),orderSaving=ref(false)
async function loadCustomers(){let result:any[]=[],number=1;while(true){const data=await api(`customers/?page_size=100&page=${number}`);result.push(...data.results);if(result.length>=data.count)break;number++}customersList.value=result}
async function openCreateOrder(){orderForm.value={user_id:null,product_id:null,quantity:1,appointment_date:'',appointment_slot:'',status:'PENDING_PAYMENT',payment_status:'UNPAID',partner_id:null};orderDialog.value=true;await loadCustomers()}
async function openEditOrder(row:any){const d=await api(`orders/${row.id}/`);orderForm.value={id:row.id,user_id:d.user_id,product_id:d.product,quantity:d.quantity,appointment_date:d.appointment_date,appointment_slot:d.appointment_slot,status:d.status,payment_status:d.payment_status,partner_id:d.partner};orderDialog.value=true;await loadCustomers()}
async function saveOrder(){const f=orderForm.value;if(!f.user_id){ElMessage.warning('请选择客户');return}if(!f.product_id){ElMessage.warning('请选择商品');return}orderSaving.value=true;try{const payload:any={user_id:f.user_id,product_id:f.product_id,quantity:f.quantity,appointment_date:f.appointment_date||null,appointment_slot:f.appointment_slot||null,status:f.status,payment_status:f.payment_status,partner_id:f.partner_id||null};if(f.id){await api(`orders/${f.id}/edit/`,'PATCH',payload)}else{await api('orders/create/','POST',payload)}ElMessage.success(f.id?'订单已更新':'订单已创建');orderDialog.value=false;await load()}catch(e){ElMessage.error((e as Error).message)}finally{orderSaving.value=false}}
async function removeOrder(row:any){try{await ElMessageBox.confirm(`确定删除订单「${row.order_no}」吗？删除后不可恢复。`, '确认删除', {type:'warning',confirmButtonText:'删除',cancelButtonText:'取消',confirmButtonClass:'el-button--danger'})}catch{return}try{await api(`orders/${row.id}/delete/`,'DELETE');ElMessage.success('已删除');await load()}catch(e){ElMessage.error((e as Error).message)}}
async function loadPartnerApps(){const path=appStatusFilter.value?`partner-applications/?status=${appStatusFilter.value}`:'partner-applications/';let result:any[]=[],number=1;while(true){const data=await api(path+`${appStatusFilter.value?'&':'?'}page_size=100&page=${number}`);result.push(...data.results);if(result.length>=data.count)break;number++}partnerApps.value=result}
async function loadPartners(){let result:any[]=[],number=1;while(true){const data=await api(`partners/?page_size=100&page=${number}`);result.push(...data.results);if(result.length>=data.count)break;number++}partnersList.value=result}
async function reviewApp(app:any,action:'approve'|'reject'){try{await api(`partner-applications/${app.id}/${action}/`,'POST',{});ElMessage.success(action==='approve'?'已通过并建立陪玩档案':'已驳回');await loadPartnerApps();await loadPartners()}catch(e){ElMessage.error((e as Error).message)}}
async function togglePartner(partner:any){try{await api(`partners/${partner.id}/edit/`,'PATCH',{is_active:!partner.is_active,version:partner.version});ElMessage.success('已更新接单开关');await loadPartners()}catch(e){ElMessage.error((e as Error).message)}}
async function openAssign(order:any){assignOrder.value=order;assignPartnerId.value=null;assignDialog.value=true;await loadPartners()}
async function doAssign(){if(!assignPartnerId.value){ElMessage.warning('请选择陪玩');return}try{await api(`orders/${assignOrder.value.id}/assign/`,'POST',{partner_id:assignPartnerId.value});ElMessage.success('已派单');assignDialog.value=false;await load()}catch(e){ElMessage.error((e as Error).message)}}
const columns=computed(()=>section.value==='products'?['id','title','game','category','price_cents','is_published','version']:section.value==='orders'?['order_no','user','product_title_snapshot','total_amount_cents','status','created_at']:section.value==='audit'?['actor','action','resource','resource_id','created_at']:section.value==='home'?['id','kind','title','target','sort_order','is_enabled','version']:section.value==='partnerApplications'?['id','nickname','game','reason','status','created_at']:section.value==='partners'?['id','nickname','game','is_active','intro','version']:['id','name',...(section.value==='categories'?['game']:[]),'sort_order','is_enabled','version'])
const labels:Record<string,string>={id:'编号',name:'名称',title:'标题',game:'游戏',category:'类型',price_cents:'售价（分）',is_published:'上架',version:'版本',order_no:'订单号',user:'用户',product_title_snapshot:'商品快照',total_amount_cents:'金额（分）',status:'状态',created_at:'创建时间',actor:'操作人',action:'动作',resource:'资源',resource_id:'对象编号',kind:'展示位置',target:'跳转',sort_order:'排序',is_enabled:'启用',nickname:'昵称',reason:'申请说明',is_active:'接单',intro:'简介'}
function show(value:any,key:string){if(key==='game'){if(value&&typeof value==='object')return value.name;return games.value.find(x=>x.id===value)?.name||value}if(key==='category')return categories.value.find(x=>x.id===value)?.name||value;if(typeof value==='boolean')return value?'是':'否';return value}
async function all(path:string){let result:any[]=[],number=1;while(true){const data=await api(`${path}/?page_size=100&page=${number}`);result.push(...data.results);if(result.length>=data.count)return result;number++}}
async function load(){busy.value=true;error.value='';try{if(!sections[section.value]){await router.replace('/overview');return}if(section.value==='overview')stats.value=await api('overview/');else if(section.value==='partnerApplications'){await loadPartnerApps()}else if(section.value==='partners'){await loadPartners()}else{const params=new URLSearchParams({page:String(page.value),q:q.value,enabled:enabled.value,game:gameFilter.value,category:categoryFilter.value,user:user.value,status:status.value,from:from.value,to:to.value});const data=await api(`${section.value}/?${params}`);rows.value=data.results;total.value=data.count}}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function init(){await session.restore();if(session.authenticated){[games.value,categories.value,products.value]=await Promise.all([all('games'),all('categories'),all('products')]);await load()}}
async function signIn(){saving.value=true;try{const result=await api('login/','POST',{username:username.value,password:password.value});setCsrfToken(result.csrf_token);password.value='';await init()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function signOut(){try{await api('logout/','POST');session.authenticated=false;rows.value=[]}catch(e){ElMessage.error((e as Error).message)}}
function edit(row?:any){form.value=row?{...row}:{sort_order:0,is_enabled:true,is_published:false,price_cents:0,original_price_cents:0,min_quantity:1,max_quantity:5,kind:'banner',target:'none',description:'',icon:'',cover_url:'',image_url:''};dialog.value=true}
async function save(){saving.value=true;try{const fields:Record<string,string[]>={games:['name','icon','sort_order','is_enabled'],categories:['name','game','description','sort_order','is_enabled'],products:['title','game','category','description','cover_url','price_cents','original_price_cents','min_quantity','max_quantity','is_published'],home:['kind','title','image_url','product','game','target','sort_order','is_enabled']};const data=Object.fromEntries([...fields[section.value],'version'].filter(k=>form.value[k]!==undefined).map(k=>[k,form.value[k]]));await api(`${section.value}/${form.value.id?form.value.id+'/':''}`,form.value.id?'PATCH':'POST',data);dialog.value=false;ElMessage.success('已保存，小程序刷新后生效');await init()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function remove(row:any){
 const resource=section.value
 const name=row.title||row.name||`#${row.id}`
 try{await ElMessageBox.confirm(`确定永久删除“${name}”吗？有关联业务记录时会拒绝删除。`, '确认删除', {type:'warning',confirmButtonText:'删除',cancelButtonText:'取消',confirmButtonClass:'el-button--danger'})}catch{return}
 try{
  await api(`${resource}/${row.id}/`,'DELETE',{version:row.version})
  ElMessage.success('已删除')
  if(rows.value.length===1&&page.value>1)page.value--
  await init()
 }catch(e){ElMessage.error((e as Error).message)}
}
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{const data=new FormData();data.append('file',file);const result=await api('upload/','POST',data);form.value[section.value==='home'?'image_url':'cover_url']=result.url}catch(e){ElMessage.error((e as Error).message)}}
async function inspect(row:any){try{detail.value=section.value==='orders'?await api(`orders/${row.id}/`):row}catch(e){ElMessage.error((e as Error).message)}}
watch(section,()=>{page.value=1;q.value='';gameFilter.value='';categoryFilter.value='';enabled.value='';if(session.authenticated)void load()})
onMounted(()=>init().catch(e=>error.value=e.message))
</script>
<template>
 <main v-if="!session.authenticated" class="login"><el-card><h1>游伴 CLUB</h1><p>运营管理 · 本地模拟环境</p><el-alert v-if="error" :title="error" type="error"/><el-form @submit.prevent="signIn"><el-form-item label="管理员"><el-input v-model="username" autocomplete="username"/></el-form-item><el-form-item label="密码"><el-input v-model="password" type="password" show-password autocomplete="current-password"/></el-form-item><el-button native-type="submit" type="primary" :loading="saving">登录管理后台</el-button></el-form></el-card></main>
 <el-container v-else class="layout"><el-aside width="210px"><h2>游伴 CLUB</h2><p class="hint">运营工作台</p><el-menu :default-active="section" @select="(value:string)=>router.push('/'+value)"><el-menu-item v-for="(name,key) in sections" :key="key" :index="key">{{name}}</el-menu-item></el-menu></el-aside><el-container><el-header><h2>{{sections[section]}}</h2><span>{{session.username}} <el-button @click="signOut">退出</el-button></span></el-header><el-main><el-alert title="本地模拟业务环境 · 不涉及真实收付款" type="info" :closable="false"/><el-alert v-if="error" :title="error" type="error"/>
 <div v-if="section==='overview'" class="stats"><el-card>商品总数<h1>{{stats.products}}</h1></el-card><el-card>上架商品<h1>{{stats.published}}</h1></el-card><el-card>模拟订单<h1>{{stats.orders}}</h1></el-card><el-card v-for="item in stats.states" :key="item.status">{{item.status}}<h2>{{item.count}}</h2></el-card></div>
 <template v-else><div class="toolbar"><el-input v-model="q" placeholder="名称 / 订单号搜索" clearable @keyup.enter="page=1;load()"/><el-select v-if="['categories','products'].includes(section)" v-model="gameFilter" placeholder="游戏" clearable><el-option v-for="g in games" :key="g.id" :value="String(g.id)" :label="g.name"/></el-select><el-select v-if="section==='products'" v-model="categoryFilter" placeholder="类型" clearable><el-option v-for="c in categories" :key="c.id" :value="String(c.id)" :label="c.name"/></el-select><el-select v-if="writable" v-model="enabled" placeholder="展示状态" clearable><el-option value="true" label="启用 / 上架"/><el-option value="false" label="停用 / 下架"/></el-select><template v-if="section==='orders'"><el-input v-model="user" placeholder="用户名"/><el-select v-model="status" placeholder="订单状态" clearable><el-option v-for="s in ['PENDING_PAYMENT','PENDING_ARRANGEMENT','PENDING_ACCEPTANCE','ACCEPTED','IN_SERVICE','PENDING_CONFIRMATION','COMPLETED','CANCELLED']" :key="s" :value="s"/></el-select><el-date-picker v-model="from" value-format="YYYY-MM-DD" placeholder="开始日期"/><el-date-picker v-model="to" value-format="YYYY-MM-DD" placeholder="结束日期"/></template><template v-if="section==='partnerApplications'"><el-select v-model="appStatusFilter" placeholder="申请状态" clearable @change="load"><el-option value="PENDING" label="待审核"/><el-option value="APPROVED" label="已通过"/><el-option value="REJECTED" label="已驳回"/></el-select></template><el-button @click="page=1;load()">查询 / 刷新</el-button><el-button v-if="writable" type="primary" @click="edit()">新增</el-button><el-button v-if="section==='orders'" type="primary" @click="openCreateOrder">新增订单</el-button></div>
 <el-table v-if="section==='partnerApplications'" :data="partnerApps" v-loading="busy" stripe><el-table-column prop="id" label="编号" width="70"/><el-table-column prop="nickname" label="申请人"/><el-table-column label="游戏" width="130"><template #default="s">{{s.row.game?.name}}</template></el-table-column><el-table-column prop="reason" label="申请说明" min-width="220"/><el-table-column label="状态" width="100"><template #default="s">{{s.row.status==='PENDING'?'待审核':s.row.status==='APPROVED'?'已通过':'已驳回'}}</template></el-table-column><el-table-column prop="created_at" label="申请时间" width="180"/><el-table-column label="操作" width="160" fixed="right"><template #default="s"><el-button v-if="s.row.status==='PENDING'" link type="primary" @click="reviewApp(s.row,'approve')">通过</el-button><el-button v-if="s.row.status==='PENDING'" link type="danger" @click="reviewApp(s.row,'reject')">驳回</el-button></template></el-table-column></el-table>
 <el-table v-else-if="section==='partners'" :data="partnersList" v-loading="busy" stripe><el-table-column prop="id" label="编号" width="70"/><el-table-column prop="nickname" label="昵称"/><el-table-column prop="username" label="账号"/><el-table-column label="游戏" width="130"><template #default="s">{{s.row.game?.name}}</template></el-table-column><el-table-column prop="intro" label="简介" min-width="180"/><el-table-column label="接单开关" width="110"><template #default="s"><el-switch :model-value="s.row.is_active" @change="togglePartner(s.row)"/></template></el-table-column></el-table>
 <el-table v-else :data="rows" v-loading="busy" stripe><el-table-column v-for="col in columns" :key="col" :label="labels[col]||col" :min-width="col==='order_no'?260:115"><template #default="scope">{{show(scope.row[col],col)}}</template></el-table-column><el-table-column label="操作" fixed="right" :width="writable?150:section==='orders'?240:100"><template #default="scope"><el-button link type="primary" @click="writable?edit(scope.row):inspect(scope.row)">{{writable?'编辑':'详情'}}</el-button><el-button v-if="writable" link type="danger" @click="remove(scope.row)">删除</el-button><template v-if="section==='orders'"><el-button link type="warning" @click="openEditOrder(scope.row)">编辑</el-button><el-button link type="danger" @click="removeOrder(scope.row)">删除</el-button><el-button v-if="scope.row.status==='PENDING_ARRANGEMENT'" link type="success" @click="openAssign(scope.row)">派单</el-button></template></template></el-table-column></el-table><el-pagination v-if="section!=='partnerApplications'&&section!=='partners'" v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next,total" @current-change="load"/></template>
 </el-main></el-container></el-container>
 <el-dialog v-model="dialog" :title="form.id?'编辑记录':'新增记录'" width="620px"><el-form label-width="110px" @submit.prevent="save"><el-form-item :label="section==='products'||section==='home'?'标题':'名称'"><el-input v-if="section==='products'||section==='home'" v-model="form.title"/><el-input v-else v-model="form.name"/></el-form-item><el-form-item v-if="['categories','products','home'].includes(section)" label="所属游戏"><el-select v-model="form.game" clearable><el-option v-for="g in games" :key="g.id" :value="g.id" :label="g.name"/></el-select></el-form-item><el-form-item v-if="section==='products'" label="商品类型"><el-select v-model="form.category"><el-option v-for="c in categories.filter(c=>c.game===form.game)" :key="c.id" :value="c.id" :label="c.name"/></el-select></el-form-item><el-form-item v-if="['categories','products'].includes(section)" label="说明"><el-input v-model="form.description" type="textarea"/></el-form-item><el-form-item v-if="section==='games'" label="图标地址"><el-input v-model="form.icon"/></el-form-item><template v-if="section==='products'"><el-form-item v-for="(label,key) in {price_cents:'售价（分）',original_price_cents:'原价（分）',min_quantity:'最小数量',max_quantity:'最大数量'}" :key="key" :label="label"><el-input-number v-model="form[key]" :min="key.includes('quantity')?1:0" :precision="0"/></el-form-item></template><template v-if="section==='home'"><el-form-item label="展示位置"><el-select v-model="form.kind"><el-option label="轮播" value="banner"/><el-option label="特价" value="special"/><el-option label="人气" value="popular"/></el-select></el-form-item><el-form-item label="内部跳转"><el-select v-model="form.target"><el-option label="不跳转" value="none"/><el-option label="游戏" value="game"/><el-option label="商品" value="product"/></el-select></el-form-item><el-form-item label="商品"><el-select v-model="form.product" filterable clearable><el-option v-for="p in products" :key="p.id" :label="p.title" :value="p.id"/></el-select></el-form-item></template><el-form-item v-if="['products','home'].includes(section)" label="封面"><input type="file" accept="image/jpeg,image/png,image/webp" @change="upload"><el-input v-if="section==='products'" v-model="form.cover_url"/><el-input v-else v-model="form.image_url"/><img v-if="form.cover_url||form.image_url" :src="form.cover_url||form.image_url" class="preview"/></el-form-item><el-form-item v-if="section!=='products'" label="排序"><el-input-number v-model="form.sort_order" :min="0" :precision="0"/></el-form-item><el-form-item label="展示状态"><el-switch v-if="section==='products'" v-model="form.is_published" active-text="上架"/><el-switch v-else v-model="form.is_enabled" active-text="启用"/></el-form-item><el-button native-type="submit" type="primary" :loading="saving">保存</el-button></el-form></el-dialog>
 <el-dialog :model-value="!!detail" title="记录详情（只读）" width="75%" @close="detail=null"><pre>{{JSON.stringify(detail,null,2)}}</pre></el-dialog>
 <el-dialog v-model="assignDialog" title="派单" width="480px"><el-form label-width="90px"><el-form-item label="订单号"><span>{{assignOrder?.order_no}}</span></el-form-item><el-form-item label="陪玩"><el-select v-model="assignPartnerId" placeholder="选择陪玩" filterable><el-option v-for="p in partnersList.filter(x=>x.is_active)" :key="p.id" :value="p.id" :label="`${p.nickname||p.username}（${p.game?.name||''}）`"/></el-select></el-form-item></el-form><template #footer><el-button @click="assignDialog=false">取消</el-button><el-button type="primary" @click="doAssign">确认派单</el-button></template></el-dialog>
 <el-dialog v-model="orderDialog" :title="orderForm.id?'编辑订单':'新增订单'" width="620px"><el-form label-width="100px"><el-form-item label="客户"><el-select v-model="orderForm.user_id" placeholder="选择客户" filterable><el-option v-for="c in customersList" :key="c.id" :value="c.id" :label="`${c.nickname}（${c.username}）`"/></el-select></el-form-item><el-form-item label="商品"><el-select v-model="orderForm.product_id" placeholder="选择商品" filterable><el-option v-for="p in products" :key="p.id" :value="p.id" :label="p.title"/></el-select></el-form-item><el-form-item label="数量"><el-input-number v-model="orderForm.quantity" :min="1" :precision="0"/></el-form-item><el-form-item label="预约日期"><el-date-picker v-model="orderForm.appointment_date" type="date" value-format="YYYY-MM-DD" placeholder="可选"/></el-form-item><el-form-item label="预约时段"><el-select v-model="orderForm.appointment_slot" placeholder="可选" clearable><el-option value="morning" label="上午"/><el-option value="afternoon" label="下午"/><el-option value="evening" label="晚上"/></el-select></el-form-item><el-form-item label="订单状态"><el-select v-model="orderForm.status"><el-option v-for="s in ['PENDING_PAYMENT','PENDING_ARRANGEMENT','PENDING_ACCEPTANCE','ACCEPTED','IN_SERVICE','PENDING_CONFIRMATION','COMPLETED','CANCELLED']" :key="s" :value="s" :label="s"/></el-select></el-form-item><el-form-item label="付款状态"><el-select v-model="orderForm.payment_status"><el-option value="UNPAID" label="未付款"/><el-option value="PAID" label="已付款"/></el-select></el-form-item><el-form-item label="陪玩"><el-select v-model="orderForm.partner_id" placeholder="可选" clearable filterable><el-option v-for="p in partnersList" :key="p.id" :value="p.id" :label="`${p.nickname||p.username}（${p.game?.name||''}）`"/></el-select></el-form-item></el-form><template #footer><el-button @click="orderDialog=false">取消</el-button><el-button type="primary" :loading="orderSaving" @click="saveOrder">{{orderForm.id?'保存修改':'创建订单'}}</el-button></template></el-dialog>
</template>
<style>body{margin:0;background:#f5f5f8;color:#303345;font-family:system-ui}h2{font-size:21px}.layout{min-height:100vh}.el-aside{background:white;border-right:1px solid #eee}.el-aside h2,.hint{padding:0 24px}.hint{color:#888}.el-header{display:flex;align-items:center;justify-content:space-between;background:white}.toolbar{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.toolbar .el-input,.toolbar .el-select{width:180px}.el-pagination{margin-top:24px}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:20px;margin-top:24px}.login{max-width:420px;margin:12vh auto}.login .el-form{margin-top:28px}.preview{width:180px;margin-top:12px}pre{white-space:pre-wrap;word-break:break-word}.el-alert{margin-bottom:12px}</style>
