# Generated by Django 5.2.17 on 2026-09-21 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_product_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepartition',
            options={'verbose_name': '游戏分区', 'verbose_name_plural': '游戏分区'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AlterField(
            model_name='gamepartition',
            name='icon',
            field=models.CharField(blank=True, max_length=255, verbose_name='图标地址'),
        ),
        migrations.AlterField(
            model_name='gamepartition',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='gamepartition',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='gamepartition',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序值'),
        ),
        migrations.AlterField(
            model_name='gamepartition',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=32, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.productcategory', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='封面地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品说明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.gamepartition', verbose_name='所属游戏'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='已上架'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_quantity',
            field=models.PositiveIntegerField(default=5, verbose_name='最大数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='最小数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price_cents',
            field=models.PositiveIntegerField(verbose_name='原价（分）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cents',
            field=models.PositiveIntegerField(verbose_name='售价（分）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='类型说明'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='core.gamepartition', verbose_name='所属游戏'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=40, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序值'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='快乐玩家', max_length=80, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
