# Generated by Django 5.2.17 on 2026-09-29 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_homeentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=64, verbose_name='小程序 AppID')),
                ('openid', models.CharField(max_length=64, verbose_name='微信 openid')),
                ('unionid', models.CharField(blank=True, max_length=64, verbose_name='微信 unionid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '微信身份',
                'verbose_name_plural': '微信身份',
                'constraints': [models.UniqueConstraint(fields=('appid', 'openid'), name='uniq_appid_openid')],
            },
        ),
    ]
