# Generated by Django 5.2.17 on 2026-10-08 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wechatidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='预约日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='appointment_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=16, null=True, verbose_name='预约时段'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING_ARRANGEMENT', 'Pending Arrangement'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('IN_SERVICE', 'In Service'), ('PENDING_CONFIRMATION', 'Pending Confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=32),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='接单开关')),
                ('intro', models.CharField(blank=True, max_length=255, verbose_name='陪玩简介')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='core.gamepartition', verbose_name='绑定游戏分区')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='陪玩账号')),
            ],
            options={
                'verbose_name': '陪玩档案',
                'verbose_name_plural': '陪玩档案',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.partner', verbose_name='陪玩'),
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='申请说明')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_applications', to='core.gamepartition', verbose_name='意向游戏分区')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '陪玩入驻申请',
                'verbose_name_plural': '陪玩入驻申请',
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='uniq_user_game_application')],
            },
        ),
    ]
