<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import PageShell from '../../components/PageShell.vue'
import AppIcon from '../../components/AppIcon.vue'
import { loginDemo } from '../../store'
import { request,setAccessToken } from '../../api/client'
import { go,detail,notify } from '../../navigation'
const agreed=ref(false), busy=ref(false)
let destination:{page:string;params:Record<string,string>}={page:'profile',params:{}}
onLoad(q=>{try{const decoded=JSON.parse(decodeURIComponent(q?.next || ''));if(['profile','messages','orders','services','detail'].includes(decoded.page)&&typeof decoded.params==='object')destination=decoded}catch{}})
async function login(){if(!agreed.value){notify('请先阅读并勾选用户协议与隐私政策');return}if(busy.value)return;busy.value=true;try{const result=await request<{access_token:string}>('/auth/dev-login/',{method:'POST',data:{}});setAccessToken(result.access_token);loginDemo();notify('登录成功');if(['profile','messages'].includes(destination.page))go(destination.page);else uni.redirectTo({url:`/pages/${destination.page}/index?${Object.entries(destination.params).map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join('&')}`})}catch(e){notify((e as Error).message||'登录失败')}finally{busy.value=false}}
</script>
<template><PageShell title=""><template #actions><button class="ui-btn muted small" @click="go('home')">先逛逛</button></template><view class="login-body"><view class="brand soft"><view class="orb one"/><view class="orb two"/><AppIcon name="game" active :size="78"/><view class="brand-name">游伴 CLUB</view><view class="muted small">一起开局，让热爱有伴</view></view><view class="welcome">欢迎来到游伴</view><view class="muted small">登录后，与同好相遇，发现更多游戏乐趣</view><view class="demo-note">当前为页面交互演示，不获取微信身份或手机号。</view><button class="ui-btn primary wide full-btn login-btn" :loading="busy" @click="login"><AppIcon name="message-white" :size="22"/>微信登录（演示）</button><view class="agreement"><checkbox-group @change="agreed=($event.detail.value.length>0)"><label class="row"><checkbox value="agree" :checked="agreed" color="#80699E" style="transform:scale(.72)"/><text>我已阅读并同意</text></label></checkbox-group><button class="ui-btn" @click="detail('terms')">《用户协议》</button><text>与</text><button class="ui-btn" @click="detail('privacy')">《隐私政策》</button></view><view class="footnote">正式接入后，首次微信登录将创建账号</view><view class="login-footer"><view class="muted small">游戏里的默契，从这里开始</view><button class="ui-btn accent small" @click="detail('support')">登录遇到问题？ 联系客服</button></view></view></PageShell></template>
<style scoped>.login-body{padding:12rpx 60rpx 40rpx}.brand{position:relative;overflow:hidden;display:flex;align-items:center;flex-direction:column;padding:64rpx 20rpx 48rpx;margin:12rpx 0 66rpx}.brand-name{font-size:48rpx;font-weight:700;margin:26rpx 0 10rpx}.orb{position:absolute;border-radius:50%}.one{width:170rpx;height:170rpx;right:28rpx;top:0;background:#d8cee7}.two{width:98rpx;height:98rpx;left:70rpx;bottom:24rpx;background:#d5e3da}.brand>image,.brand-name,.brand>.small{z-index:1}.welcome{font-size:49rpx;font-weight:700;margin-bottom:24rpx}.login-btn{margin-top:34rpx;height:100rpx;font-size:30rpx}.agreement{display:flex;flex-wrap:wrap;align-items:center;justify-content:center;font-size:21rpx;color:#747486;margin-top:26rpx}.agreement button{font-size:21rpx;color:#8875aa;line-height:2}.login-footer{text-align:center;margin-top:84rpx}.login-footer button{margin:20rpx auto}</style>
